### ISSUE TITLE
Add assertions that only log messages on failure

### ISSUE THREAD

**Issue by bmblb** [bryntum/siesta#11]
Usecase: common assertions that are useful but leave too many messages in the test log.
Proposal: 
```
foo = true;
bar = false;
t.optFail.ok(foo, 'Foo is ok') // doesn't log anything
t.optFail.ok(bar, 'Bar is ok') // logs 'bar is not ok'
```

It could be handy to make this a modifier for regular assertion, much like `.not.`

**Comment by canonic-epicure** [comment]
Duplicate of https://github.com/bryntum/siesta/issues/2

**Comment by canonic-epicure** [comment]
I'm inclining more to the lambda wrapper as in #2 instead of the `optFail` magic property.

**Comment by bmblb** [comment]
@canonic-epicure this property is not more magic than `.not.`, it is merely a modifier for the assertion behavior. I do not insist on the name if it makes any difference. maybe `t.silent.is` would gain more approval
